new aqua version, completions supabase stripe, bitwarden secret

diff --git a/home/private_dot_config/exact_private_ssh/personal-keys.d/run_onchange_before_cache-ssh-keys.sh.tmpl b/home/private_dot_config/exact_private_ssh/personal-keys.d/run_onchange_before_cache-ssh-keys.sh.tmpl
--- a/home/private_dot_config/exact_private_ssh/personal-keys.d/run_onchange_before_cache-ssh-keys.sh.tmpl
+++ b/home/private_dot_config/exact_private_ssh/personal-keys.d/run_onchange_before_cache-ssh-keys.sh.tmpl
@@ -3,11 +3,14 @@ set -eufo pipefail
 
 # {{ includeTemplate "universal/next-update" . }}
 
-if [ ! "$(command -v dcli)" ]; then
-  echo "Dashlane CLI command was not found"
+if [ ! "$(command -v bw)" ]; then
+  echo "Bitwarden CLI command was not found"
   exit 1
-elif ! dcli a whoami &> /dev/null; then
-  echo "Please login to Dashlane"
+elif ! bw --nointeraction --quiet login --check; then
+  echo "Please login to Bitwarden and set the BW_SESSION environment variable"
+  exit 1
+elif ! bw --nointeraction --quiet unlock --check; then
+  echo "Please unlock Bitwarden and set the BW_SESSION environment variable"
   exit 1
 fi
 
@@ -20,6 +23,6 @@ secrets=(
 
 for secret in "${secrets[@]}"
 do
-    dcli n $secret > "{{ .cache.secrets.dir }}/$secret"
+    bw get notes $secret > "{{ .cache.secrets.dir }}/$secret"
     chmod 600 "{{ .cache.secrets.dir }}/$secret"
 done
